version: "3.7"
services:
  app:
    build:
      args:
        user: 1000
        uid: 1000
      context: ./
      dockerfile: ./devops/conf/Dockerfile
    container_name: parser-app
    restart: on-failure
    working_dir: /var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - "PHP_IDE_CONFIG=serverName=parser-docker.local"
    volumes:
      - ./:/var/www
      - ./devops/php-ext/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./devops/php-ext/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - parser

  nginx:
    image: nginx:latest
    container_name: parser-nginx
    restart: on-failure
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./devops/conf/nginx_default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - parser
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]

networks:
  parser:
    driver: bridge
